---

- name: update package cache if older than 1 hour
  apt: update_cache=yes cache_valid_time=3600

- name: install packages
  apt: name="{{item}}" state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - vim
    - iftop
    - htop