---
- name: Create SD card image for unattended raspbian install
  hosts: localhost
  connection: local
  pre_tasks:
    - include_vars: config/options.yml
    - set_fact: authorized_keys_file="{{dir.noobs}}/authorized_keys"

    - name: make sure NOOBS directory exists
      file: path="{{dir.noobs}}" state=directory mode=0755

    - file: path="{{authorized_keys_file}}" state=absent

    - shell: cat "{{item}}" >> "{{authorized_keys_file}}"
      with_fileglob: './config/ssh/authorized_keys/**'

    - shell: echo "" >> "{{authorized_keys_file}}"

  roles:
    - role: prepare_image
      target_dir: "{{dir.noobs}}"
      tmp_dir: "{{dir.tmp}}"
