---
- name: Create SD card image for unattended raspbian install
  hosts: localhost
  connection: local
  pre_tasks:
    - include_vars: config/options.yml
    - set_fact: SSH_PUBLIC_KEYS="{{ lookup('fileglob', './config/ssh/authorized_keys/**') }}"

  roles:
    - role: prepare_image
      target_dir: "{{dir.noobs}}"
      tmp_dir: "{{dir.tmp}}"
    #- role: raspbi-config