---

- name: update packages
  apt: update_cache=yes upgrade=full

- name: make sure update-notifer-common is installed
  apt: package=update-notifier-common state=latest

- name: check if reboot is necessary
  stat: path=/var/run/reboot-required
  register: reboot_required

- name: reboot
  command: shutdown -r now "Ansible updates triggered"
  async: 0
  poll: 0
  ignore_errors: true
  when: reboot_required.stat.exists

- name: waiting for host to come back
  local_action: wait_for host={{ inventory_hostname }}
                state=started
  sudo: false
  when: reboot_required.stat.exists